# Generated by Django 2.2.28 on 2024-12-04 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_code', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Код подразделения')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('manager_code', models.CharField(max_length=10, verbose_name='Код работника руководителя')),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('equipment_code', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Код оборудования')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
                'db_table': 'equipment',
            },
        ),
        migrations.CreateModel(
            name='EquipmentCategory',
            fields=[
                ('category_code', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Код категории оборудования')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('depreciation_rate', models.FloatField(verbose_name='Процент амортизационных отчислений')),
            ],
            options={
                'verbose_name': 'Категория оборудования',
                'verbose_name_plural': 'Категории оборудования',
                'db_table': 'equipment_category',
            },
        ),
        migrations.CreateModel(
            name='InventoryCard',
            fields=[
                ('card_number', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Номер карточки')),
                ('equipment_code', models.CharField(max_length=10, verbose_name='Код оборудования')),
                ('completeness_sign', models.CharField(max_length=15, verbose_name='Признак комплектности')),
                ('category_code', models.CharField(max_length=10, verbose_name='Код категории оборудования')),
                ('initial_cost', models.FloatField(verbose_name='Первоначальная стоимость')),
                ('total_depreciation_amount', models.FloatField(verbose_name='Общая сумма амортизаций')),
                ('release_date', models.DateField(verbose_name='Дата выпуска оборудования')),
                ('commissioning_date', models.DateField(verbose_name='Дата ввода в эксплуатацию')),
                ('department_code', models.CharField(max_length=10, verbose_name='Код подразделения')),
                ('employee_code', models.CharField(max_length=10, verbose_name='Код работника')),
            ],
            options={
                'verbose_name': 'Инвентарная карточка',
                'verbose_name_plural': 'Инвентарные карточки',
                'db_table': 'inventory_card',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_code', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Код работника')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('department_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.Department', verbose_name='Код подразделения')),
            ],
            options={
                'verbose_name': 'Работник',
                'verbose_name_plural': 'Работники',
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='Completeness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_number', models.CharField(max_length=10, verbose_name='Номер позиции')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('note', models.CharField(max_length=100, verbose_name='Примечание')),
                ('card_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.InventoryCard', verbose_name='Номер карточки')),
            ],
            options={
                'verbose_name': 'Комплектность',
                'verbose_name_plural': 'Комплектности',
                'db_table': 'completeness',
                'unique_together': {('card_number', 'position_number')},
            },
        ),
        migrations.CreateModel(
            name='Accrual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0, verbose_name='Сумма начислений')),
                ('month', models.PositiveIntegerField(verbose_name='Месяц')),
                ('year', models.PositiveIntegerField(verbose_name='Год')),
                ('card_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.InventoryCard', verbose_name='Номер карточки')),
            ],
            options={
                'verbose_name': 'Начисление',
                'verbose_name_plural': 'Начисления',
                'db_table': 'accrual',
                'unique_together': {('card_number', 'month', 'year')},
            },
        ),
    ]
