# Generated by Django 2.2.28 on 2024-12-08 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accrual',
            name='card_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accruals', to='record.InventoryCard', verbose_name='Номер карточки'),
        ),
        migrations.AlterField(
            model_name='completeness',
            name='card_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completeness', to='record.InventoryCard', verbose_name='Номер карточки'),
        ),
        migrations.AlterField(
            model_name='department',
            name='manager_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to='record.Employee', verbose_name='Код работника руководителя'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='record.Department', verbose_name='Код подразделения'),
        ),
        migrations.AlterField(
            model_name='inventorycard',
            name='category_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.EquipmentCategory', verbose_name='Код категории оборудования'),
        ),
        migrations.AlterField(
            model_name='inventorycard',
            name='department_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.Department', verbose_name='Код подразделения'),
        ),
        migrations.AlterField(
            model_name='inventorycard',
            name='employee_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.Employee', verbose_name='Код работника'),
        ),
        migrations.AlterField(
            model_name='inventorycard',
            name='equipment_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.Equipment', verbose_name='Код оборудования'),
        ),
    ]
