# Generated by Django 2.2.28 on 2024-12-08 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0004_auto_20241208_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completeness',
            name='position_number',
            field=models.CharField(editable=False, max_length=10, verbose_name='Номер позиции'),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_code',
            field=models.CharField(editable=False, max_length=10, primary_key=True, serialize=False, verbose_name='Код подразделения'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_code',
            field=models.CharField(editable=False, max_length=10, primary_key=True, serialize=False, verbose_name='Код работника'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_code',
            field=models.CharField(editable=False, max_length=10, primary_key=True, serialize=False, verbose_name='Код оборудования'),
        ),
        migrations.AlterField(
            model_name='inventorycard',
            name='card_number',
            field=models.CharField(editable=False, max_length=10, primary_key=True, serialize=False, verbose_name='Номер карточки'),
        ),
        migrations.AlterUniqueTogether(
            name='completeness',
            unique_together={('position_number',)},
        ),
    ]
