# Generated by Django 2.2.28 on 2024-12-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0005_auto_20241208_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completeness',
            name='position_number',
            field=models.CharField(max_length=10, verbose_name='Номер позиции'),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Код подразделения'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Код работника'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Код оборудования'),
        ),
        migrations.AlterField(
            model_name='equipmentcategory',
            name='category_code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Код категории оборудования'),
        ),
        migrations.AlterField(
            model_name='inventorycard',
            name='card_number',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Номер карточки'),
        ),
    ]
