# Generated by Django 2.2.28 on 2024-12-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0006_auto_20241208_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_code',
            field=models.CharField(blank=True, max_length=10, primary_key=True, serialize=False, verbose_name='Код работника'),
        ),
    ]
