# Generated by Django 2.2.28 on 2024-12-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0007_auto_20241208_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accrual',
            name='month',
            field=models.PositiveIntegerField(blank=True, verbose_name='Месяц'),
        ),
        migrations.AlterField(
            model_name='accrual',
            name='year',
            field=models.PositiveIntegerField(blank=True, verbose_name='Год'),
        ),
    ]
