# Generated by Django 2.2.28 on 2024-12-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0009_auto_20241208_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorycard',
            name='card_number',
            field=models.CharField(blank=True, max_length=10, primary_key=True, serialize=False, verbose_name='Номер карточки'),
        ),
    ]
