# Generated by Django 2.2.28 on 2024-12-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0010_auto_20241208_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorycard',
            name='completeness_sign',
            field=models.CharField(choices=[('FULL', 'Полная комплектация'), ('PARTIAL', 'Частичная комплектация'), ('INCOMPLETE', 'Неполная комплектация')], max_length=15, verbose_name='Признак комплектности'),
        ),
    ]
