# Generated by Django 2.2.28 on 2024-12-08 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0011_auto_20241208_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorycard',
            name='completeness_sign',
            field=models.CharField(choices=[('Полная комплектация', 'Полная комплектация'), ('Частичная комплектация', 'Частичная комплектация'), ('Неполная комплектация', 'Неполная комплектация')], max_length=15, verbose_name='Признак комплектности'),
        ),
    ]
