# Generated by Django 2.2.28 on 2024-12-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0013_auto_20241208_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completeness',
            name='position_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Номер позиции'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_code',
            field=models.CharField(blank=True, max_length=30, primary_key=True, serialize=False, verbose_name='Код оборудования'),
        ),
        migrations.AlterField(
            model_name='inventorycard',
            name='completeness_sign',
            field=models.CharField(choices=[('Полная комплектация', 'Полная комплектация'), ('Частичная комплектация', 'Частичная комплектация'), ('Неполная комплектация', 'Неполная комплектация')], max_length=30, verbose_name='Признак комплектности'),
        ),
    ]
