# Generated by Django 2.2.28 on 2024-12-10 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0015_auto_20241210_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accrual',
            name='month',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Январь'), (2, 'Февраль'), (3, 'Март'), (4, 'Апрель'), (5, 'Май'), (6, 'Июнь'), (7, 'Июль'), (8, 'Август'), (9, 'Сентябрь'), (10, 'Октябрь'), (11, 'Ноябрь'), (12, 'Декабрь')], verbose_name='Месяц'),
        ),
        migrations.AlterField(
            model_name='accrual',
            name='year',
            field=models.PositiveIntegerField(blank=True, choices=[(2014, '2014'), (2015, '2015'), (2016, '2016'), (2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024')], verbose_name='Год'),
        ),
        migrations.AlterField(
            model_name='completeness',
            name='position_number',
            field=models.CharField(blank=True, editable=False, max_length=10, verbose_name='Номер позиции'),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_code',
            field=models.CharField(blank=True, editable=False, max_length=10, primary_key=True, serialize=False, verbose_name='Код подразделения'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_code',
            field=models.CharField(blank=True, editable=False, max_length=10, primary_key=True, serialize=False, verbose_name='Код работника'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_code',
            field=models.CharField(blank=True, editable=False, max_length=10, primary_key=True, serialize=False, verbose_name='Код оборудования'),
        ),
        migrations.AlterField(
            model_name='equipmentcategory',
            name='category_code',
            field=models.CharField(blank=True, editable=False, max_length=10, primary_key=True, serialize=False, verbose_name='Код категории оборудования'),
        ),
        migrations.AlterField(
            model_name='inventorycard',
            name='card_number',
            field=models.CharField(blank=True, editable=False, max_length=10, primary_key=True, serialize=False, verbose_name='Номер карточки'),
        ),
    ]
