# Generated by Django 2.2.28 on 2024-12-11 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0016_auto_20241210_2318'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='completeness',
            unique_together={('card_number', 'position_number')},
        ),
    ]
